### Importing the module

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

### Load the Data

In [2]:
df = pd.read_csv("cars.csv")

In [3]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df["brand"].nunique()

32

In [5]:
df["brand"].value_counts()

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [6]:
df["fuel"].value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

In [7]:
df["owner"].value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

### One Hot Encoding Using Pandas

In [8]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df.shape

(8128, 5)

In [10]:
pd.get_dummies(df,columns=["owner","fuel"])

brand  km_driven  selling_price  owner_First Owner  \
0      Maruti     145500         450000                  1   
1       Skoda     120000         370000                  0   
2       Honda     140000         158000                  0   
3     Hyundai     127000         225000                  1   
4      Maruti     120000         130000                  1   
...       ...        ...            ...                ...   
8123  Hyundai     110000         320000                  1   
8124  Hyundai     119000         135000                  0   
8125   Maruti     120000         382000                  1   
8126     Tata      25000         290000                  1   
8127     Tata      25000         290000                  1   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  
0                     0         0            1         0            0  
1                     0         0            1         0            0  
2                     1         0            0         0            1  
3                     0         0            1         0            0  
4                     0         0            0         0            1  
...                 ...       ...          ...       ...          ...  
8123                  0         0            0         0            1  
8124                  0         0            1         0            0  
8125                  0         0            1         0            0  
8126                  0         0            1         0            0  
8127                  0         0            1         0            0  

[8128 rows x 12 columns]

In [11]:
pd.get_dummies(df,columns=["owner","fuel"]).shape

(8128, 12)

### N-1 One Hot Encoding 

In [12]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [13]:
df.shape

(8128, 5)

In [14]:
pd.get_dummies(df,columns=["owner","fuel"],drop_first=True)

brand  km_driven  selling_price  owner_Fourth & Above Owner  \
0      Maruti     145500         450000                           0   
1       Skoda     120000         370000                           0   
2       Honda     140000         158000                           0   
3     Hyundai     127000         225000                           0   
4      Maruti     120000         130000                           0   
...       ...        ...            ...                         ...   
8123  Hyundai     110000         320000                           0   
8124  Hyundai     119000         135000                           1   
8125   Maruti     120000         382000                           0   
8126     Tata      25000         290000                           0   
8127     Tata      25000         290000                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  \
0                      0                     0                  0   
1                      1                     0                  0   
2                      0                     0                  1   
3                      0                     0                  0   
4                      0                     0                  0   
...                  ...                   ...                ...   
8123                   0                     0                  0   
8124                   0                     0                  0   
8125                   0                     0                  0   
8126                   0                     0                  0   
8127                   0                     0                  0   

      fuel_Diesel  fuel_LPG  fuel_Petrol  
0               1         0            0  
1               1         0            0  
2               0         0            1  
3               1         0            0  
4               0         0            1  
...           ...       ...          ...  
8123            0         0            1  
8124            1         0            0  
8125            1         0            0  
8126            1         0            0  
8127            1         0            0  

[8128 rows x 10 columns]

In [15]:
pd.get_dummies(df,columns=["owner","fuel"],drop_first=True).shape

(8128, 10)

### One Hot Encoding Using Sklearn

In [16]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [17]:
X_train,X_test,y_train,y_test = train_test_split(df.drop("selling_price",axis=1),df["selling_price"],test_size=0.2,random_state=2)

In [18]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [19]:
X_test.head()

brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [20]:
ohe = OneHotEncoder(drop="first",sparse=False)

In [21]:
ohe.fit_transform(X_train[["fuel","owner"]])

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [22]:
ohe.fit_transform(X_train[["fuel","owner"]])

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [23]:
X_train_new = ohe.fit_transform(X_train[["fuel","owner"]])
X_test_new = ohe.transform(X_test[["fuel","owner"]])

In [24]:
X_train_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [25]:
X_train[["brand","km_driven"]].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

In [26]:
np.hstack((X_train[["brand","km_driven"]].values,X_train_new)).shape

(6502, 9)

### One Hot Encoding with top Categories

In [27]:
counts = df["brand"].value_counts()

In [28]:
counts

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [29]:
repl = counts[counts<=100].index

In [30]:
pd.get_dummies(df["brand"].replace(repl,"uncommon"))

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
0       0          0     0      0        0         0       1        0      0   
1       0          0     0      0        0         0       0        0      1   
2       0          0     0      1        0         0       0        0      0   
3       0          0     0      0        1         0       0        0      0   
4       0          0     0      0        0         0       1        0      0   
...   ...        ...   ...    ...      ...       ...     ...      ...    ...   
8123    0          0     0      0        1         0       0        0      0   
8124    0          0     0      0        1         0       0        0      0   
8125    0          0     0      0        0         0       1        0      0   
8126    0          0     0      0        0         0       0        0      0   
8127    0          0     0      0        0         0       0        0      0   

      Tata  Toyota  Volkswagen  uncommon  
0        0       0           0         0  
1        0       0           0         0  
2        0       0           0         0  
3        0       0           0         0  
4        0       0           0         0  
...    ...     ...         ...       ...  
8123     0       0           0         0  
8124     0       0           0         0  
8125     0       0           0         0  
8126     1       0           0         0  
8127     1       0           0         0  

[8128 rows x 13 columns]